################################################################################## Version: @version@
# +--------------â–„â–„â–„-- â€šâ€”â€”. -â–„--â–„-â–„--â–„-â–„-â–„â–„â–„â–„â–„---------------------------------------------------+ #
# |              â–ˆâ–„â–„â–€ (â€œâ€¡â€¡â€) â–ˆâ–„â–„â–€ â–ˆâ–„â–„â–€ â–ˆ   â–ˆ         Support available at: discord.gg/mTaHuK6BVa | #
# |              â–ˆâ–„â–„â–ˆ  \__/  â–ˆ  â–ˆ â–ˆ  â–ˆ â–ˆ   â–ˆ                    â€š-.                              | #
# |         â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€” ((_)) â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”          | #
# |                                                             â€˜-â€™                              | #
# |         .|'''.|  |''||''|     |     '||''|.    ..|'''.|      |     |''||''| '||''''|         | #
# |         ||..  '     ||       |||     ||   ||  .|'     '     |||       ||     ||  .           | #
# |          ''|||.     ||      |  ||    ||''|'   ||    ....   |  ||      ||     ||''|           | #
# |        .     '||    ||     .''''|.   ||   |.  '|.    ||   ;â€™   |.     ||     ||              | #
# |         '....|'    .||.   .|.  .||. .||.  '|'  ''|...'|  .|.  .||.   .||.   .||.....|        | #
# +----------------------------------------------------------------------------------------------+ #
# |                        https://spigotmc.org/resources/stargate.87978/                        | #
# +----------------------------------------------+-----------------------------------------------+ #
# |      Documentation: https://git.io/JDclf     |       Bug Reports: https://git.io/Jc6jW       | #
# +----------------------------------------------+-----------------------------------------------+ #
####################################################################################################
# TODO: REPLACE THE ABOVE ANCII ART.

# +----------------------------------------------------------------------------------------------+ #
# |                                      General Preferences                                     | #
# +----------------------------------------------------------------------------------------------+ #

# Where should StarGate look for configurations detailing portal colouring, highlights, et cetera?
#  Options:
#	NONE:  StarGate will follow the "Aesthetic Tweaks" section of the core plugin's config.yml
#	FILE:  StarGate will follow StargateCustomizations/colours.yml (sgrewritten.org/styleFile)
#	THEME: StarGate will follow a theme generated by ColourWizard (sgrewritten.org/ColourWizard)
style_source: NONE

# If the above is set to "THEME", SGC will import a ColourWizard theme based on the code below.
# If the above is set to "NONE" or "FILE", this configuration option will be ignored.
theme_code: '23hgf324h8ygbg8345hfg9834h5f89465gft69873245g689f34g5869f432g5896fg298546gf289645gf89'

# +----------------------------------------------------------------------------------------------+ #
# |                                           Technical                                          | #
# +----------------------------------------------------------------------------------------------+ #

# |                                          [ Logging ]                                         | #
# |__                   How much information should stargate send to console?                  __| #

# Possible Values:
#   |=> SEVERE (Not recommended).
#   |   - ğ‡ğ¢ğğ ğğ¯ğğ«ğ²ğ­ğ¡ğ¢ğ§ğ . ğ‘‚ğ‘›ğ‘™ğ‘¦ ğ‘ğ‘Ÿğ‘–ğ‘›ğ‘¡ ğ‘¡ğ‘œ ğ‘ğ‘œğ‘›ğ‘ ğ‘œğ‘™ğ‘’ ğ‘–ğ‘“ ğ‘ğ‘™ğ‘¢ğ‘”ğ‘–ğ‘› ğ‘“ğ‘ğ‘¡ğ‘ğ‘™ğ‘™ğ‘¦ ğ‘ğ‘Ÿğ‘ğ‘ â„ğ‘’ğ‘ 
#   |=> WARNING (Recommended for large and well-tested production implementations).
#   |   - ğ‡ğ¢ğğ ğ§ğ¨ğ«ğ¦ğšğ¥ ğ›ğğ¡ğšğ¯ğ¢ğ¨ğ®ğ«. ğ‘‚ğ‘›ğ‘™ğ‘¦ ğ‘ğ‘Ÿğ‘–ğ‘›ğ‘¡ ğ‘ğ‘œğ‘¡ğ‘’ğ‘›ğ‘¡ğ‘–ğ‘ğ‘™ ğ‘–ğ‘ ğ‘ ğ‘¢ğ‘’ğ‘ .
#   |=> INFO (Recommended for most production implementations).
#   |   - ğğ«ğ¢ğ§ğ­ ğ§ğ¨ğ«ğ¦ğšğ¥ ğ›ğğ¡ğšğ¯ğ¢ğ¨ğ®ğ«. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘ğ‘œğ‘Ÿğ‘¡ğ‘ğ‘™ ğ‘’ğ‘£ğ‘’ğ‘›ğ‘¡ğ‘  (ğ‘¢ğ‘ ğ‘ğ‘”ğ‘’, ğ‘ğ‘Ÿğ‘’ğ‘ğ‘¡ğ‘–ğ‘œğ‘›, ğ‘‘ğ‘’ğ‘ ğ‘¡ğ‘Ÿğ‘¢ğ‘ğ‘¡ğ‘–ğ‘œğ‘›, ğ‘’ğ‘¡ğ‘.)
#   |=> CONFIG (Useful for configuring preproduction instances).
#   |   - ğğ«ğ¢ğ§ğ­ ğ©ğğ«ğ¦ğ¢ğ¬ğ¬ğ¢ğ¨ğ§ ğœğ¡ğğœğ¤ğ¬. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘â„ğ‘’ğ‘ğ‘˜ğ‘  ğ‘šğ‘ğ‘‘ğ‘’ ğ‘¡ğ‘œ ğ‘‘ğ‘’ğ‘¡ğ‘’ğ‘Ÿğ‘šğ‘–ğ‘›ğ‘’ ğ‘–ğ‘“ ğ‘ğ‘™ğ‘ğ‘¦ğ‘’ğ‘Ÿğ‘  ğ‘ğ‘ğ‘› ğ‘ğ‘’ğ‘Ÿğ‘“ğ‘œğ‘Ÿğ‘š ğ‘ğ‘› ğ‘ğ‘ğ‘¡ğ‘–ğ‘œğ‘›.
#   |=> FINE (Recommended for basic troubleshooting).
#   |   - ğğ«ğ¢ğ§ğ­ ğ¥ğ¢ğ¦ğ¢ğ­ğğ ğğğ›ğ®ğ  ğ¢ğ§ğŸğ¨. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘”ğ‘’ğ‘›ğ‘’ğ‘Ÿğ‘ğ‘™ ğ‘ğ‘™ğ‘¢ğ‘”ğ‘–ğ‘› ğ‘’ğ‘£ğ‘’ğ‘›ğ‘¡ğ‘  (ğ‘™ğ‘œğ‘ğ‘‘ğ‘–ğ‘›ğ‘”, ğ‘‘ğ‘–ğ‘ ğ‘ğ‘ğ‘™ğ‘–ğ‘›ğ‘”, ğ‘ğ‘œğ‘›ğ‘›ğ‘’ğ‘ğ‘¡ğ‘–ğ‘œğ‘›ğ‘ , ğ‘’ğ‘¡ğ‘.).
#   |=> FINER (Recommended for some addon developers).
#   |   - ğğ«ğ¢ğ§ğ­ ğ¦ğ¨ğ¬ğ­ ğğğ›ğ®ğ  ğ¢ğ§ğŸğ¨. ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘šğ‘’ğ‘ ğ‘ ğ‘ğ‘”ğ‘’ğ‘  ğ‘‘ğ‘’ğ‘¡ğ‘ğ‘–ğ‘™ğ‘–ğ‘›ğ‘” ğ‘¡â„ğ‘’ ğ‘ğ‘™ğ‘¢ğ‘”ğ‘–ğ‘›'ğ‘  ğ‘™ğ‘œğ‘”ğ‘–ğ‘ ğ‘ğ‘›ğ‘‘ ğ‘ğ‘’â„ğ‘ğ‘£ğ‘–ğ‘œğ‘¢ğ‘Ÿ.
#   |=> FINEST (Only used by StarGate's core development team).
#   |   - ğğ«ğ¢ğ§ğ­ ğğ¯ğğ«ğ²ğ­ğ¡ğ¢ğ§ğ . ğ‘ƒğ‘Ÿğ‘–ğ‘›ğ‘¡ğ‘  ğ‘™ğ‘–ğ‘¡ğ‘’ğ‘Ÿğ‘ğ‘™ğ‘™ğ‘¦ ğ‘’ğ‘£ğ‘’ğ‘Ÿğ‘¦ğ‘¡â„ğ‘–ğ‘›ğ‘”, ğ‘–ğ‘›ğ‘ğ‘™ğ‘¢ğ‘‘ğ‘–ğ‘›ğ‘” ğ‘›ğ‘¢ğ‘šğ‘’ğ‘Ÿğ‘œğ‘¢ğ‘  ğ‘ ğ‘¡ğ‘ğ‘ğ‘˜ ğ‘¡ğ‘Ÿğ‘ğ‘ğ‘’ğ‘ .
logging_level: INFO

# |                                           [ Debug ]                                          | #
# |__     These settings are provided to help developers diagnose issues with this plugin.     __| #

# An internal value used by the plugin to determine how old your config is.
# Please do not change this.
config_version: 0